services:
  db:
    image: postgres:latest
    container_name: banco_de_dados
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
        - "${PORTA_EXTERNA}:${PORTA_INTERNA}"
  etl:
    build: src/ETL/
    container_name: ELT
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}